# Generated by Django 5.0.4 on 2024-04-18 14:08

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_email_valid', models.BooleanField(default=False)),
                ('profile_img_url', models.CharField(blank=True, max_length=1000)),
                ('is_active_for_proposals', models.BooleanField(default=False)),
                ('is_investor', models.BooleanField(default=False)),
                ('is_startup', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('registration_date', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('investor_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('contact_phone', models.CharField(max_length=128)),
                ('contact_email', models.CharField(max_length=128)),
                ('investment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interests', models.CharField(max_length=500)),
                ('number_for_investor_validation', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investor',
                'verbose_name_plural': 'Investors',
                'db_table': 'investors',
            },
        ),
    ]
