# Generated by Django 5.0.4 on 2024-04-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='investor',
            old_name='investor_id',
            new_name='id',
        ),
    ]
