# Generated by Django 5.0.4 on 2024-04-19 11:09

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='registration_date',
            field=models.DateTimeField(default=django.db.models.functions.datetime.Now()),
        ),
    ]
