# Generated by Django 5.0.4 on 2024-04-22 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_username_remove_investor_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='surname',
            new_name='last_name',
        ),
        migrations.DeleteModel(
            name='EmailConfirmationToken',
        ),
    ]
