# Generated by Django 5.0.4 on 2024-04-23 08:53

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('startup_name', models.CharField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('industries', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=128)),
                ('contact_email', models.CharField(blank=True, max_length=128)),
                ('number_for_startup_validation', models.IntegerField(null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('registration_date', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'startups',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('goals', models.CharField(max_length=255)),
                ('budget_needed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_ready', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('industry', models.CharField(max_length=255)),
                ('promo_photo_url', models.CharField(blank=True, max_length=1000)),
                ('promo_video_url', models.CharField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed')], max_length=20)),
                ('registration_date', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('investors', models.ManyToManyField(blank=True, related_name='participated_projects', to='users.investor')),
                ('subscribers', models.ManyToManyField(blank=True, related_name='subscribed_projects', to='users.investor')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='startups.startup')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
    ]
