# Generated by Django 5.0.4 on 2024-04-19 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startup',
            old_name='company_id',
            new_name='id',
        ),
    ]
