# Generated by Django 5.0.4 on 2024-04-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_rename_company_id_startup_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='industry',
            field=models.CharField(choices=[('tech', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Health Care'), ('education', 'Education'), ('economics', 'Economics')], max_length=255),
        ),
    ]
